frontend:
  enabled: true

  # https://github.com/stakater/application/blob/main/application/values.yaml
  replicas: 1

  deployment:
    image:
      repository: ""
      tag: ""
      pullPolicy: IfNotPresent
  
  ingress:
    enabled: false
    hosts:
      - host: frontend.local
        paths:
          - path: /
    tls: []

  vpa:
    enabled: true


backend:
  enabled: true
  
  # https://github.com/stakater/application/blob/main/application/values.yaml
  replicas: 1
  
  deployment:
    image:
      repository: ""
      tag: ""
      pullPolicy: IfNotPresent
  
  ingress:
    enabled: false
    hosts:
      - host: backend.local
        paths:
          - path: /
    tls: []

  vpa:
    enabled: true